export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const CHECK_USERNAME_REQUEST = "CHECK_USERNAME_REQUEST"
export const CHECK_USERNAME_SUCCESS = "CHECK_USERNAME_SUCCESS"
export const CHECK_USERNAME_FAIL = "CHECK_USERNAME_FAIL"

export const PROFILE_REQUEST = "PROFILE_REQUEST"
export const PROFILE_SUCCESS = "PROFILE_SUCCESS"
export const PROFILE_FAIL = "PROFILE_FAIL"

