import wait_10 from './wait10_s.json'
import wait_15 from './wait15_s.json'
import wait_20 from './wait20_s.json'
import wait_25 from './wait25_s.json'
import wait_30 from './wait30_s.json'
import wait_35 from './wait35_s.json'
import wait_40 from './wait40_s.json'
import wait_45 from './wait45_s.json'
import wait_50 from './wait50_s.json'
import wait_R_G from './wait red to green.json'
import ArrowUp from './arrow_up.json'
import ArrowRight from './arrow_right.json'
import ArrowLeft from './left_arrow.json'
import RedtoGreen from './wait red to green.json'
import waitPulse from './wait_pulse.json'
import ReversePlay from './btn_play_reverse.json'
import timeout from './timeout.json'
import ReverseWait from './wait_reverse.json'
import missed from './missed.json'
export const AllAnimation = {timeout,missed,wait_10,wait_15,wait_20,wait_25,wait_30,wait_35,wait_40,wait_45,wait_50,wait_R_G,ArrowUp,ArrowLeft,ArrowRight,RedtoGreen,waitPulse,ReversePlay,ReverseWait}